### PR TITLE
Resolve compiler warnings.

### PR DESCRIPTION
**Pull request by eric-s-raymond**
A prototype needed void in its signature.

You had a variable name shadowing a typedef. This is why it's considered good practice to use a _t suffix when naming typedefs. 

Modified code passes all tests.  Public API is unchanged.

### CODE REVIEW

**Comment by dfoxfranke** [comment]
I'll merge the change to add `void` to the type signature and swap `const static` for `static const`. But using the `_t` suffix is really *bad* practice because that's reserved for system headers, see POSIX.1-2017 §2.2.2. Are you messing with the gcc warning flags to trigger the messages you're getting? Because `-Wshadow` isn't in CMakeList.txt and I don't want it there. Shadowing is a perfectly legal, well-defined, and reasonable thing to do, and to have a warning for this case in particular is just unreasonably chatty, because the only time variable names actually shadow typedefs is when they're used in `sizeof`, which these aren't.

**Comment by eric-s-raymond** [comment]
>But using the _t suffix is really bad practice because that's reserved for system headers

First I ever heard of *that* theory.  I looked in 2.2.2  at http://pubs.opengroup.org/ of POSIX.1-2017 and didn't find any such reservation.  I've been marking my typedefs with _t for decades.

Yes, I had -Wall enabled. I usually do.  I think it's good practice. One finds bugs that way.

**Comment by dfoxfranke** [comment]
Are we both looking at http://pubs.opengroup.org/onlinepubs/9699919799/functions/V2_chap02.html? It's right there in the bottom row of the table.

libaes_siv already builds with `-Wall`. `-Wshadow` isn't included in `-Wall`.

**Comment by eric-s-raymond** [comment]
You're right.  I was looking for it in running text and missed that.

I didn't set -Wshadow explicitly.  OTOH, this is not the first time I've encountered apparently random variations across platforms and minor compiler versions in what -Wall implies.

**Comment by dfoxfranke** [comment]
It may be a quirk of Ubuntu's GCC patches. They mess with a bunch of default flags: https://wiki.ubuntu.com/ToolChain/CompilerFlags. This is not one they've documented having messed with, but I wouldn't be surprised. Do the warnings go away if you add an explicit `-Wno-shadow`?

**Comment by dfoxfranke** [comment]
We determined OOB that seeing these warnings was the result of an attempt to drop files from the project into a foreign build system, which obviously is not something that's supported. I've resolved the nits with `const static` and void function prototypes via 504228f9d018e113c54fa3730efd937f5f3b27c1.

**Pull request closed without merging**
